symbol = ">"

[env_var]
VERSION = "v1.0.0"
COMMIT_MSG = "Update README.md"

[exec]
cpp = [
    "g++ -g -O2 -std=c++17 -W $FILE_PATH -o $FILE_PATH_WITHOUT_EXT",
    "$FILE_PATH_WITHOUT_EXT",
]
py = { cmd = "py -3 $FILE_PATH", sh = "python3 $FILE_PATH" }

[misc]
echo = "echo $0"
# When the contents of "cmd" and "sh" match,
# they can be specified together by "common".
echo_confirm = { common = "echo $0", confirm = true }
# This is equivalent to the following:
# echo_confirm = { cmd = "echo $0", sh = "echo $0", confirm = true }
echo2 = ["echo $0", "echo ${1}_$2"]
push = { common = [
    "git add --all",
    'git commit -m "$COMMIT_MSG"',
    "git push origin master",
], confirm = true }
release = { common = [
    "git add --all",
    'git commit -m "Release $VERSION"',
    "git push origin master",
    "git tag -d $VERSION",
    'git tag -a $VERSION -m "$VERSION"',
    "git push origin $VERSION",
], confirm = true }
